---
- name: Add or update the user's password
  hosts: all

  tasks:
          - name: Change george password
            user:
                    name: george
                    update_password: always
                    password: "{{ new_password|password_hash('sha512') }}"
