---
- name: Create a directory then download Tomcat
  hosts: all

  tasks:
          - name: Create a directory
            file:
                    path: /opt/tomcat
                    state: directory
                    mode: 0755
                    owner: root
                    group: root

          - name: Download Tomcat
            get_url:
                    url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.25/bin/apache-tomcat-10.1.25.tar.gz
                    dest: /opt/tomcat
                    mode: 0755
