---
- name: Create a User
  hosts: all

  tasks:
          - name: Creating a user named george
            user:
                    name: george
                    home: /home/george
                    shell: /bin/bash
